// Code generated by Kitex v0.5.0. DO NOT EDIT.
package blogpostservice

import (
	server "github.com/cloudwego/kitex/server"
	blog "github.com/weblogs/kitex_gen/github/com/weblogs/blog"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler blog.BlogPostService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
