// Code generated by Validator v0.1.4. DO NOT EDIT.

package blog

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *CreatePostRequest) IsValid() error {
	if len(p.Title) < int(1) {
		return fmt.Errorf("field Title min_len rule failed, current value: %d", len(p.Title))
	}
	if p.AuthorID <= int64(0) {
		return fmt.Errorf("field AuthorID gt rule failed, current value: %v", p.AuthorID)
	}
	if len(p.Content) < int(0) {
		return fmt.Errorf("field Content min_len rule failed, current value: %d", len(p.Content))
	}
	if len(p.Content) > int(10485760) {
		return fmt.Errorf("field Content max_len rule failed, current value: %d", len(p.Content))
	}
	return nil
}
func (p *CreatePostResponse) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *UpdatePostRequest) IsValid() error {
	return nil
}
func (p *UpdatePostResponse) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *DeletePostRequest) IsValid() error {
	return nil
}
func (p *DeletePostResponse) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("filed BaseResp not valid, %w", err)
		}
	}
	return nil
}
